services:
  comandas.api:
    image: ${DOCKER_REGISTRY-}comandasapi
    build:
      context: .
      dockerfile: comandas.api/Dockerfile
    networks:
      - comandas
  postgres: 
    image: postgres:16.6
    restart: always
    environment: 
      POSTGRES_DB: comandas_db
      POSTGRES_USER: adm
      POSTGRES_PASSWORD: 4524
    volumes:
      - comandasdb_data:/var/lib/postgresql/data 
    ports:
      - "5432:5432" 
    networks: 
      - comandas
  redis:
    image: redis:latest
    ports: 
      - "6379:6379"
    networks:
      - comandas
  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      REDIS_HOSTS: local:redis:6379
    ports:
      - "8081:8081"
    networks:
      - comandas
    depends_on:
      - redis
networks:
  comandas:
volumes:  
  comandasdb_data:

