// <auto-generated />
using Comandas.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace comandas.api.Migrations
{
    [DbContext(typeof(ComandasDBContext))]
    [Migration("20250415174840_v6")]
    partial class v6
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Comandas.API.Models.CardapioItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("TX_DESCRICAO");

                    b.Property<bool>("PossuiPreparo")
                        .HasColumnType("boolean")
                        .HasColumnName("IC_PREPARO");

                    b.Property<decimal>("Preco")
                        .HasColumnType("numeric")
                        .HasColumnName("VL_PRECO");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("NO_ITEM");

                    b.HasKey("Id");

                    b.ToTable("TB_CARDAPIO_ITEM", (string)null);
                });

            modelBuilder.Entity("Comandas.API.Models.Comanda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("NomeCliente")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("NO_CLIENTE");

                    b.Property<int>("NumeroMesa")
                        .HasColumnType("integer")
                        .HasColumnName("NU_MESA");

                    b.Property<int>("SituacaoComanda")
                        .HasColumnType("integer")
                        .HasColumnName("IC_SITUACAO");

                    b.HasKey("Id");

                    b.ToTable("TB_COMANDA", (string)null);
                });

            modelBuilder.Entity("Comandas.API.Models.ComandaItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CardapioItemId")
                        .HasColumnType("integer")
                        .HasColumnName("ID_CARDAPIO_ITEM");

                    b.Property<int>("ComandaId")
                        .HasColumnType("integer")
                        .HasColumnName("ID_COMANDA");

                    b.HasKey("Id");

                    b.HasIndex("CardapioItemId");

                    b.HasIndex("ComandaId");

                    b.ToTable("TB_COMANDA_ITEM", (string)null);
                });

            modelBuilder.Entity("Comandas.API.Models.Mesa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("NumeroMesa")
                        .HasColumnType("integer")
                        .HasColumnName("NUM_MESA");

                    b.Property<int>("SituacaoMesa")
                        .HasColumnType("integer")
                        .HasColumnName("IC_SITUACAO");

                    b.HasKey("Id");

                    b.ToTable("TB_MESA", (string)null);
                });

            modelBuilder.Entity("Comandas.API.Models.PedidoCozinha", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ComandaId")
                        .HasColumnType("integer")
                        .HasColumnName("ID_COMANDA");

                    b.Property<int>("SituacaoId")
                        .HasColumnType("integer")
                        .HasColumnName("IC_SITUACAO");

                    b.HasKey("Id");

                    b.HasIndex("ComandaId");

                    b.ToTable("TB_PEDIDO_COZINHA", (string)null);
                });

            modelBuilder.Entity("Comandas.API.Models.PedidoCozinhaItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ComanadaItemId")
                        .HasColumnType("integer")
                        .HasColumnName("ID_COMANDA_ITEM");

                    b.Property<int>("PedidoCozinhaId")
                        .HasColumnType("integer")
                        .HasColumnName("ID_PEDIDO_COZINHA");

                    b.HasKey("Id");

                    b.HasIndex("ComanadaItemId");

                    b.HasIndex("PedidoCozinhaId");

                    b.ToTable("TB_PEDIDO_COZINHA_ITEM", (string)null);
                });

            modelBuilder.Entity("Comandas.API.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tx_email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("no_ususario");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tx_senha");

                    b.HasKey("Id");

                    b.ToTable("tbl_usuario", (string)null);
                });

            modelBuilder.Entity("Comandas.API.Models.ComandaItem", b =>
                {
                    b.HasOne("Comandas.API.Models.CardapioItem", "CardapioItem")
                        .WithMany()
                        .HasForeignKey("CardapioItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Comandas.API.Models.Comanda", "Comanda")
                        .WithMany("ComandaItems")
                        .HasForeignKey("ComandaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CardapioItem");

                    b.Navigation("Comanda");
                });

            modelBuilder.Entity("Comandas.API.Models.PedidoCozinha", b =>
                {
                    b.HasOne("Comandas.API.Models.Comanda", "Comanda")
                        .WithMany()
                        .HasForeignKey("ComandaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comanda");
                });

            modelBuilder.Entity("Comandas.API.Models.PedidoCozinhaItem", b =>
                {
                    b.HasOne("Comandas.API.Models.ComandaItem", "ComandaItem")
                        .WithMany()
                        .HasForeignKey("ComanadaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Comandas.API.Models.PedidoCozinha", "PedidoCozinha")
                        .WithMany("PedidoCozinhaItems")
                        .HasForeignKey("PedidoCozinhaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComandaItem");

                    b.Navigation("PedidoCozinha");
                });

            modelBuilder.Entity("Comandas.API.Models.Comanda", b =>
                {
                    b.Navigation("ComandaItems");
                });

            modelBuilder.Entity("Comandas.API.Models.PedidoCozinha", b =>
                {
                    b.Navigation("PedidoCozinhaItems");
                });
#pragma warning restore 612, 618
        }
    }
}
