// <auto-generated />
using Comandas.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Comandas.Data.Migrations
{
    [DbContext(typeof(ComandasDBContext))]
    partial class ComandasDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Comandas.Domain.CardapioItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tx_descricao");

                    b.Property<bool>("PossuiPreparo")
                        .HasColumnType("boolean")
                        .HasColumnName("ic_preparo");

                    b.Property<decimal>("Preco")
                        .HasColumnType("numeric")
                        .HasColumnName("vl_preco");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("no_item");

                    b.HasKey("Id");

                    b.ToTable("tb_cardapio_item", "dbo");
                });

            modelBuilder.Entity("Comandas.Domain.Comanda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("NomeCliente")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("no_cliente");

                    b.Property<int>("NumeroMesa")
                        .HasColumnType("integer")
                        .HasColumnName("nu_mesa");

                    b.Property<int>("SituacaoComanda")
                        .HasColumnType("integer")
                        .HasColumnName("ic_situacao");

                    b.HasKey("Id");

                    b.ToTable("tb_comanda", "dbo");
                });

            modelBuilder.Entity("Comandas.Domain.ComandaItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CardapioItemId")
                        .HasColumnType("integer")
                        .HasColumnName("id_cardapio_item");

                    b.Property<int>("ComandaId")
                        .HasColumnType("integer")
                        .HasColumnName("id_comanda");

                    b.HasKey("Id");

                    b.HasIndex("CardapioItemId");

                    b.HasIndex("ComandaId");

                    b.ToTable("tb_comanda_item", "dbo");
                });

            modelBuilder.Entity("Comandas.Domain.Mesa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("NumeroMesa")
                        .HasColumnType("integer")
                        .HasColumnName("nu_mesa");

                    b.Property<int>("SituacaoMesa")
                        .HasColumnType("integer")
                        .HasColumnName("ic_situacao");

                    b.HasKey("Id");

                    b.ToTable("tb_mesa", "dbo");
                });

            modelBuilder.Entity("Comandas.Domain.PedidoCozinha", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ComandaId")
                        .HasColumnType("integer")
                        .HasColumnName("id_comanda");

                    b.Property<int>("SituacaoId")
                        .HasColumnType("integer")
                        .HasColumnName("ic_situacao");

                    b.HasKey("Id");

                    b.HasIndex("ComandaId");

                    b.ToTable("tb_pedido_cozinha", "dbo");
                });

            modelBuilder.Entity("Comandas.Domain.PedidoCozinhaItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ComanadaItemId")
                        .HasColumnType("integer")
                        .HasColumnName("id_comanda_item");

                    b.Property<int>("PedidoCozinhaId")
                        .HasColumnType("integer")
                        .HasColumnName("id_pedido_cozinha");

                    b.HasKey("Id");

                    b.HasIndex("ComanadaItemId");

                    b.HasIndex("PedidoCozinhaId");

                    b.ToTable("tb_pedido_cozinha_item", "dbo");
                });

            modelBuilder.Entity("Comandas.Domain.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tx_email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("no_ususario");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tx_senha");

                    b.HasKey("Id");

                    b.ToTable("tb_usuario", "dbo");
                });

            modelBuilder.Entity("Comandas.Domain.ComandaItem", b =>
                {
                    b.HasOne("Comandas.Domain.CardapioItem", "CardapioItem")
                        .WithMany()
                        .HasForeignKey("CardapioItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Comandas.Domain.Comanda", "Comanda")
                        .WithMany("ComandaItems")
                        .HasForeignKey("ComandaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CardapioItem");

                    b.Navigation("Comanda");
                });

            modelBuilder.Entity("Comandas.Domain.PedidoCozinha", b =>
                {
                    b.HasOne("Comandas.Domain.Comanda", "Comanda")
                        .WithMany()
                        .HasForeignKey("ComandaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comanda");
                });

            modelBuilder.Entity("Comandas.Domain.PedidoCozinhaItem", b =>
                {
                    b.HasOne("Comandas.Domain.ComandaItem", "ComandaItem")
                        .WithMany()
                        .HasForeignKey("ComanadaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Comandas.Domain.PedidoCozinha", "PedidoCozinha")
                        .WithMany("PedidoCozinhaItems")
                        .HasForeignKey("PedidoCozinhaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComandaItem");

                    b.Navigation("PedidoCozinha");
                });

            modelBuilder.Entity("Comandas.Domain.Comanda", b =>
                {
                    b.Navigation("ComandaItems");
                });

            modelBuilder.Entity("Comandas.Domain.PedidoCozinha", b =>
                {
                    b.Navigation("PedidoCozinhaItems");
                });
#pragma warning restore 612, 618
        }
    }
}
